services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    networks:
      - backend-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/api/node_modules
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - backend-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_APP_API_URL=http://localhost:4000/api/v1
      - VITE_CLERK_PUBLISHABLE_KEY=pk_test_c3VtbWFyeS1sb2JzdGVyLTEuY2xlcmsuYWNjb3VudHMuZGV2JA
    depends_on:
      - backend

networks:
  backend-network:
    driver: bridge

volumes:
  postgres-data:
