FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY api/package*.json ./api/

RUN npm install --prefix ./api

COPY . .

WORKDIR /usr/src/app/api

RUN npx prisma generate --schema=./src/database/prisma/schema.prisma

RUN npm run build

EXPOSE 4000

CMD ["sh", "-c", "npx prisma migrate reset --force --schema=./src/database/prisma/schema.prisma && npx prisma db seed && node dist/index.js"]